package com.example.miniTrackingProject.common;

public enum OrderStatus {
    PENDING, CONFIRMED, PACKED, SHIPPED, IN_TRANSIT, DELIVERED, CANCELLED,RETURN_PENDING, RETURNED, FAILED, WAREHOUSE_RECEIVED, RESTOCKED, REFUNDED
}
